name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_KEY }}'
          aws-region: ap-south-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.0  

      - name: Initialize Terraform
        run: terraform init

      - name: Deploy VPC and EC2
        run: terraform apply -auto-approve
      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov
        run: checkov -d .

      - name: Install Terratest
        run: go get -u github.com/gruntwork-io/terratest/modules/terraform

      - name: Run Terratest
        run: go test -v test/terratest/
